# Generated by Django 6.0.4 on 2026-05-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('class_id', models.IntegerField()),
                ('description', models.TextField()),
                ('is_safety_critical', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['class_id'],
            },
        ),
        migrations.CreateModel(
            name='DefectDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('roboflow', 'Roboflow'), ('custom', 'Custom Upload'), ('combined', 'Combined')], max_length=50)),
                ('roboflow_url', models.URLField(blank=True, null=True)),
                ('local_path', models.CharField(max_length=500)),
                ('num_images', models.IntegerField(default=0)),
                ('num_classes', models.IntegerField(default=6)),
                ('classes_list', models.JSONField(default=list)),
                ('yaml_config', models.FileField(blank=True, upload_to='dataset_configs/')),
                ('date_downloaded', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_architecture', models.CharField(default='yolov8n', max_length=50)),
                ('epochs', models.IntegerField(default=50)),
                ('image_size', models.IntegerField(default=416)),
                ('batch_size', models.IntegerField(default=16)),
                ('custom_weight', models.FloatField(default=0.5, help_text='0.0=public data only, 1.0=custom data only')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_mAP50', models.FloatField(blank=True, null=True)),
                ('final_precision', models.FloatField(blank=True, null=True)),
                ('final_recall', models.FloatField(blank=True, null=True)),
                ('model_file', models.FileField(blank=True, upload_to='trained_models/')),
                ('training_log', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defect_detector.defectdataset')),
            ],
        ),
    ]
